# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='reason',
            field=models.CharField(choices=[('op1', 'Exec Assistant'), ('op2', 'Operational Review'), ('op3', 'Other')], default='op1', max_length=4),
        ),
    ]
