# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 01:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactus_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 12, 1, 15, 25, 449696, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
