# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 01:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160812_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
