# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160812_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='details',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='reason',
        ),
        migrations.AddField(
            model_name='contactus',
            name='brief_description',
            field=models.TextField(default=datetime.datetime(2016, 11, 17, 3, 55, 8, 973968, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='company_name',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='contactus',
            name='how_did_you_hear_about_us',
            field=models.CharField(choices=[('op1', 'Word of Mouth'), ('op2', 'Facebook'), ('op3', 'Google Search'), ('op4', 'Other')], default='op1', max_length=4),
        ),
        migrations.AddField(
            model_name='contactus',
            name='service',
            field=models.CharField(choices=[('op1', 'Consultation'), ('op2', 'Administrative Assistance'), ('op3', 'Other')], default='op1', max_length=4),
        ),
        migrations.AddField(
            model_name='contactus',
            name='website',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
