# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20161117_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_philosophy', models.TextField()),
                ('cm_about_us', models.TextField()),
                ('cm_team_para_one', models.TextField()),
                ('cm_team_para_two', models.TextField()),
                ('cm_service_admin', models.TextField()),
                ('cm_service_consultation', models.TextField()),
                ('cm_date_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
