# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contentmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='cm_title',
            field=models.CharField(default=datetime.datetime(2016, 11, 17, 5, 41, 26, 431880, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
