# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_contentmanagement_cm_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_completed', models.BooleanField()),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(max_length=500)),
                ('priority', models.IntegerField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ContentManagement')),
            ],
        ),
    ]
